p = 'docs/method-rules.md'
s = open(p, encoding='utf-8', newline='').read()
CRLF = "\r\n" if "\r\n" in s[:4000] else "\n"

anchor_start = s.find('| **★★★★ S138-g**')
assert anchor_start > 0
eol = s.find(CRLF, anchor_start)
assert eol > 0

rows = [
 '| **★★★★★ S140T2-a** | **the RECOMMENDED EXPERIMENT in a settled document, and the arm you are about to build from it** | S140 Tier 1 §5 prescribed *"write a sentinel into `Velocity`, wait ≥3 frames, read `CMC+0x16B0`"* and gave a decision rule whose null branch is *"payload still `(0,0,0)` ⇒ it did not run [M]"* | **that null branch is DEGENERATE, and the SAME DOCUMENT\'s §7 says so** — with `Velocity` resting at `(0,0,0)` and `NewObject` zero-filling, "snapshotted a zero" and "never written" are THE SAME BYTES. The two sections were never reconciled | ⇒ ★★★ **pre-poison the destination.** Writing a distinctive value into the buffer first makes never-written and written-with-zeros different bytes, costs nothing, and needs no write to the field under test at all. MEASURED: poison overwritten within 250 ms on both components, then 396/400 sentinel hits on a 2 ms burst. **A prescription and its own caveat sitting in one document is not a contradiction you can leave for the reader — one of them is wrong.** |',
 '| **★★★★★ S140T2-b** | **the game thread, as the place your own arm runs** | the handoff\'s recipe (write → wait ≥3 frames → read) implemented literally inside the arm. `BsLadderStep` runs ON THE GAME THREAD inside `OnPI`, so every `Sleep()` in it **blocks the game thread and no frames pass** | the read would have been GUARANTEED to see the un-updated payload, and the result would have been published as *"StartNewPhysics does not run"* — **manufacturing exactly the false negative the whole Tier existed to correct** ⚠ and a worker thread spawned INSIDE the arm fails too: the ladder holds the thread ~4.4-5.2 s longer through its trailing `Sleep(750)` + A2 census | ⇒ ★★ **an instrument that consumes the resource it is measuring reads a frozen world.** Sample from the **existing** worker thread after the arm releases the game thread (the `RM_DROPPLANE` B4 precedent), and carry an independent frames-are-passing control — here `TimeSinceFallingStart`, measured advancing at **1.002×** real time on both pawns |',
 '| **★★★★ S140T2-c** | **`hitsGT`, the shim\'s own game-thread dispatch counter, quoted in a source comment as `[M]`** | `tutorial_launch.cpp:15883`: *"one hit is all this world state delivers (flight 1: hitsGT=1, hot list EMPTY)"* | `OnPI` increments `g_hitsGT` **AFTER** its `if(g_done||g_inHook) return;` early-out, so **a one-shot ladder can never report more than 1, whatever the dispatch rate**, and the `hot:` profile window was measured while the ladder\'s own A0 census held the thread. Both numbers are SELF-INFLICTED | the decisive control was already on disk: `docs/fk24-s128-poolspawn-RESULT.txt`, **identical `KFSNAME=""` and identical `swapped=17563`**, but a PACED ladder that releases the thread — **`hitsGT=588`, ~73 dispatches/s.** ⇒ ★★ **a counter gated behind an early-out measures the gate, not the world.** It had foreclosed the multi-hit design permanently |',
 '| **★★★★ S140T2-d** | **a `#else` branch added to keep an arm\'s skip message symmetrical with its siblings** | one `Marker("ARM H NOT COMPILED IN")` line inside `#if/#else`, compiled into the builds where the arm is absent | it moved the regression gate `gasattr` **`2fcc2536e21f18e3` → `6d81e34e675f97f1`** — **while leaving its `.text` SIZE at 137,728 bytes.** The repo\'s own *"diff the hash, never the size"* rule demonstrating itself, on the very commit that was trying to preserve the gates | ⇒ ★★ **a skip message compiled into the CONTROL builds is not free.** Put arm code behind a preprocessor `#if` **with no `#else`**, and re-digest every gate after every edit — the gates then reproduced EXACTLY, which is the only reason the flight was interpretable |',
 '| **★★★★ S140T2-e** | **a recorded regression-gate digest, `driverecompute a2a952babfed256b`** | it appears in `CLAUDE.md` and three docs as an S138/S139 gate | `build.ps1` gives `driverecompute` `-DKBSPSARMS=0xA0` and `gasattr-ctrl` `-DKBSPSARMS=0x0A0` — **the same value** — so from one source state they MUST be byte-identical, and today both build to `4465ebc4d7168c03`. The archived DLL has a different `.text` size (134,144 vs 134,656) ⇒ **that artifact predates a source change and was never rebuilt** | ⇒ ★★ **a recorded digest is a claim about an ARTIFACT, not about the SOURCE. Reproduce it from HEAD before calling it a gate.** Same pattern as `botspawn_readonly`. `text_digest.py --dupes` flags the pair as a HAZARD independently — **run it** |',
 '| **★★★ S140T2-f** | **`BsLadderStep`\'s own two documented controls** | the A0→A1 "stability control" and the post-call *"give a spawned actor a tick to register"* `Sleep` | **both windows are game-thread-blocked by the ladder itself.** Actor spawning is game-thread-only, so `A0 == A1` cannot see the class of event it exists to exclude — it means *the census is repeatable*, not *nothing spawned*. And **no tick can occur** while the game thread sleeps in our own frame: the census works because `GUObjectArray` registration is SYNCHRONOUS | ⇒ ⚠⚠ **the dangerous corollary a successor will trip on: anything that genuinely needs a TICK has NOT happened when that ladder reads it** — deferred `BeginPlay`, the component registration queue, `AddPlayerState` reaching `PlayerArray`, and **any movement simulation whatsoever**. Fix the comment; it is an instrument-artifact generator |',
 '| **★★★ S140T2-g** | **a trusted, already-calibrated probe carried forward across a retraction** | `cmc_earlyout_readout.py`, the S139 instrument, still printed a confident `RANK-1 VERDICT` (`S1` vs `S2`) computed from `CMC+0x16C8` | S140 Tier 1 had **retracted that inference weeks-equivalent earlier** — the latch reads 0 in every world. The probe would have handed a successor a confident wrong answer **from the repo\'s own trusted instrument** | ⇒ ★★ **when a claim is retracted, grep the TOOLS, not just the docs.** A retraction that does not reach the instrument that produced the claim has not landed. **Fixed**: the block now prints the retraction plus a payload recogniser and raw hex |',
]

s = s[:eol] + CRLF + CRLF.join(rows) + s[eol:]
open(p, 'w', encoding='utf-8', newline='').write(s)
print("inserted %d rows" % len(rows))
