"""AngelScript opcode table for SUPERVIVE's FORKED engine.

GENERATED by gen_opcodes.py -- do not hand-edit.
Source of truth: the game's own asBCInfo[256] read out of
  G:/git/Supervive Revival Project/dumps/merged.dump.exe
at RVA 0x084A22C0, with asBCTypeSize[] at RVA 0x084B45A0 (verified against a
second identical copy at 0x084EA4A0).

The operand layouts below are DERIVED from the asEBCType names using
AngelScript's positional accessor rule (SWORDARG0/1/2 at +2/+4/+6, INT/QWORD
args on the next free dword boundary). That derivation independently
reproduces all 22 entries of the binary's own asBCTypeSize table, which is
what pins the layout of the fork-added type 21 (asBCTYPE_W_rW_ARG).
"""

# Decodable opcodes are 0..MAXBYTECODE-1. asBC_MAXBYTECODE in the fork's own
# header reads 212 (from the dummy slots), and slot 212 is a real entry, so the
# fork appended an opcode without bumping the constant. We trust the table.
MAXBYTECODE = 213
PSEUDO_OPS = [251, 252, 253, 254, 255]  # never present in a serialized stream

TYPE_NAMES = ['INFO', 'NO_ARG', 'W_ARG', 'wW_ARG', 'DW_ARG', 'rW_DW_ARG', 'QW_ARG', 'DW_DW_ARG', 'wW_rW_rW_ARG', 'wW_QW_ARG', 'wW_rW_ARG', 'rW_ARG', 'wW_DW_ARG', 'wW_rW_DW_ARG', 'rW_rW_ARG', 'wW_W_ARG', 'QW_DW_ARG', 'rW_QW_ARG', 'W_DW_ARG', 'rW_W_DW_ARG', 'rW_DW_DW_ARG', 'W_rW_ARG']
TYPE_SIZE = [0, 1, 1, 1, 2, 2, 3, 3, 2, 3, 2, 1, 2, 3, 2, 2, 4, 3, 2, 3, 3, 2]

# type_id -> [(field_name, byte_offset_within_instruction, kind)]
TYPE_LAYOUT = {
     0: [],   # INFO
     1: [],   # NO_ARG
     2: [('W0', 2, 's16')],   # W_ARG
     3: [('wW0', 2, 's16')],   # wW_ARG
     4: [('DW', 4, 'i32')],   # DW_ARG
     5: [('rW0', 2, 's16'), ('DW', 4, 'i32')],   # rW_DW_ARG
     6: [('QW', 4, 'u64')],   # QW_ARG
     7: [('DW', 4, 'i32'), ('DW1', 8, 'i32')],   # DW_DW_ARG
     8: [('wW0', 2, 's16'), ('rW1', 4, 's16'), ('rW2', 6, 's16')],   # wW_rW_rW_ARG
     9: [('wW0', 2, 's16'), ('QW', 4, 'u64')],   # wW_QW_ARG
    10: [('wW0', 2, 's16'), ('rW1', 4, 's16')],   # wW_rW_ARG
    11: [('rW0', 2, 's16')],   # rW_ARG
    12: [('wW0', 2, 's16'), ('DW', 4, 'i32')],   # wW_DW_ARG
    13: [('wW0', 2, 's16'), ('rW1', 4, 's16'), ('DW', 8, 'i32')],   # wW_rW_DW_ARG
    14: [('rW0', 2, 's16'), ('rW1', 4, 's16')],   # rW_rW_ARG
    15: [('wW0', 2, 's16'), ('W1', 4, 's16')],   # wW_W_ARG
    16: [('QW', 4, 'u64'), ('DW', 12, 'i32')],   # QW_DW_ARG
    17: [('rW0', 2, 's16'), ('QW', 4, 'u64')],   # rW_QW_ARG
    18: [('W0', 2, 's16'), ('DW', 4, 'i32')],   # W_DW_ARG
    19: [('rW0', 2, 's16'), ('W1', 4, 's16'), ('DW', 8, 'i32')],   # rW_W_DW_ARG
    20: [('rW0', 2, 's16'), ('DW', 4, 'i32'), ('DW1', 8, 'i32')],   # rW_DW_DW_ARG
    21: [('W0', 2, 's16'), ('rW1', 4, 's16')],   # W_rW_ARG
}

# opcode -> (name, type_id, size_dwords, stack_inc)
# stack_inc 0xFFFF is AngelScript's 'variable stack effect' sentinel.
OPCODES = {
      0: ('PopPtr'          ,  1, 1,     -2),
      1: ('PshGPtr'         ,  6, 3,      2),
      2: ('PshC4'           ,  4, 2,      1),
      3: ('PshV4'           , 11, 1,      1),
      4: ('PSF'             , 11, 1,      2),
      5: ('SwapPtr'         ,  1, 1,      0),
      6: ('NOT'             , 11, 1,      0),
      7: ('PshG4'           ,  6, 3,      1),
      8: ('LdGRdR4'         ,  9, 3,      0),
      9: ('CALL'            ,  4, 2,  65535),
     10: ('RET'             ,  2, 1,  65535),
     11: ('JMP'             ,  4, 2,      0),
     12: ('JZ'              ,  4, 2,      0),
     13: ('JNZ'             ,  4, 2,      0),
     14: ('JS'              ,  4, 2,      0),
     15: ('JNS'             ,  4, 2,      0),
     16: ('JP'              ,  4, 2,      0),
     17: ('JNP'             ,  4, 2,      0),
     18: ('TZ'              ,  1, 1,      0),
     19: ('TNZ'             ,  1, 1,      0),
     20: ('TS'              ,  1, 1,      0),
     21: ('TNS'             ,  1, 1,      0),
     22: ('TP'              ,  1, 1,      0),
     23: ('TNP'             ,  1, 1,      0),
     24: ('NEGi'            , 11, 1,      0),
     25: ('NEGf'            , 11, 1,      0),
     26: ('NEGd'            , 11, 1,      0),
     27: ('INCi16'          ,  1, 1,      0),
     28: ('INCi8'           ,  1, 1,      0),
     29: ('DECi16'          ,  1, 1,      0),
     30: ('DECi8'           ,  1, 1,      0),
     31: ('INCi'            ,  1, 1,      0),
     32: ('DECi'            ,  1, 1,      0),
     33: ('INCf'            ,  1, 1,      0),
     34: ('DECf'            ,  1, 1,      0),
     35: ('INCd'            ,  1, 1,      0),
     36: ('DECd'            ,  1, 1,      0),
     37: ('IncVi'           , 11, 1,      0),
     38: ('DecVi'           , 11, 1,      0),
     39: ('BNOT'            , 11, 1,      0),
     40: ('BAND'            ,  8, 2,      0),
     41: ('BOR'             ,  8, 2,      0),
     42: ('BXOR'            ,  8, 2,      0),
     43: ('BSLL'            ,  8, 2,      0),
     44: ('BSRL'            ,  8, 2,      0),
     45: ('BSRA'            ,  8, 2,      0),
     46: ('COPY'            , 18, 2,     -2),
     47: ('PshC8'           ,  6, 3,      2),
     48: ('PshVPtr'         , 11, 1,      2),
     49: ('RDSPtr'          ,  1, 1,      0),
     50: ('CMPd'            , 14, 2,      0),
     51: ('CMPu'            , 14, 2,      0),
     52: ('CMPf'            , 14, 2,      0),
     53: ('CMPi'            , 14, 2,      0),
     54: ('CMPIi'           ,  5, 2,      0),
     55: ('CMPIf'           ,  5, 2,      0),
     56: ('CMPIu'           ,  5, 2,      0),
     57: ('JMPP'            ,  5, 2,      0),
     58: ('PopRPtr'         ,  1, 1,     -2),
     59: ('PshRPtr'         ,  1, 1,      2),
     60: ('STR'             ,  2, 1,      3),
     61: ('CALLSYS'         ,  6, 3,  65535),
     62: ('CALLBND'         ,  4, 2,  65535),
     63: ('SUSPEND'         ,  1, 1,      0),
     64: ('ALLOC'           , 16, 4,  65535),
     65: ('FREE'            ,  9, 3,      0),
     66: ('LOADOBJ'         , 11, 1,      0),
     67: ('STOREOBJ'        ,  3, 1,      0),
     68: ('GETOBJ'          , 21, 2,      0),
     69: ('REFCPY'          ,  1, 1,     -2),
     70: ('CHKREF'          ,  1, 1,      0),
     71: ('GETOBJREF'       , 21, 2,      0),
     72: ('GETREF'          , 21, 2,      0),
     73: ('PshNull'         ,  1, 1,      2),
     74: ('ClrVPtr'         ,  3, 1,      0),
     75: ('OBJTYPE'         ,  6, 3,      2),
     76: ('TYPEID'          ,  4, 2,      1),
     77: ('SetV4'           , 12, 2,      0),
     78: ('SetV8'           ,  9, 3,      0),
     79: ('ADDSi'           , 18, 2,      0),
     80: ('CpyVtoV4'        , 10, 2,      0),
     81: ('CpyVtoV8'        , 10, 2,      0),
     82: ('CpyVtoR4'        , 11, 1,      0),
     83: ('CpyVtoR8'        , 11, 1,      0),
     84: ('CpyVtoG4'        , 17, 3,      0),
     85: ('CpyRtoV4'        ,  3, 1,      0),
     86: ('CpyRtoV8'        ,  3, 1,      0),
     87: ('CpyGtoV4'        ,  9, 3,      0),
     88: ('WRTV1'           , 11, 1,      0),
     89: ('WRTV2'           , 11, 1,      0),
     90: ('WRTV4'           , 11, 1,      0),
     91: ('WRTV8'           , 11, 1,      0),
     92: ('RDR1'            ,  3, 1,      0),
     93: ('RDR2'            ,  3, 1,      0),
     94: ('RDR4'            ,  3, 1,      0),
     95: ('RDR8'            ,  3, 1,      0),
     96: ('LDG'             ,  6, 3,      0),
     97: ('LDV'             , 11, 1,      0),
     98: ('PGA'             ,  6, 3,      2),
     99: ('CmpPtr'          , 14, 2,      0),
    100: ('VAR'             , 11, 1,      2),
    101: ('iTOf'            , 10, 2,      0),
    102: ('fTOi'            , 10, 2,      0),
    103: ('uTOf'            , 10, 2,      0),
    104: ('fTOu'            , 10, 2,      0),
    105: ('sbTOi'           , 10, 2,      0),
    106: ('swTOi'           , 10, 2,      0),
    107: ('ubTOi'           , 10, 2,      0),
    108: ('uwTOi'           , 10, 2,      0),
    109: ('dTOi'            , 10, 2,      0),
    110: ('dTOu'            , 10, 2,      0),
    111: ('dTOf'            , 10, 2,      0),
    112: ('iTOd'            , 10, 2,      0),
    113: ('uTOd'            , 10, 2,      0),
    114: ('fTOd'            , 10, 2,      0),
    115: ('ADDi'            ,  8, 2,      0),
    116: ('SUBi'            ,  8, 2,      0),
    117: ('MULi'            ,  8, 2,      0),
    118: ('DIVi'            ,  8, 2,      0),
    119: ('MODi'            ,  8, 2,      0),
    120: ('ADDf'            ,  8, 2,      0),
    121: ('SUBf'            ,  8, 2,      0),
    122: ('MULf'            ,  8, 2,      0),
    123: ('DIVf'            ,  8, 2,      0),
    124: ('MODf'            ,  8, 2,      0),
    125: ('ADDd'            ,  8, 2,      0),
    126: ('SUBd'            ,  8, 2,      0),
    127: ('MULd'            ,  8, 2,      0),
    128: ('DIVd'            ,  8, 2,      0),
    129: ('MODd'            ,  8, 2,      0),
    130: ('ADDIi'           , 13, 3,      0),
    131: ('SUBIi'           , 13, 3,      0),
    132: ('MULIi'           , 13, 3,      0),
    133: ('ADDIf'           , 13, 3,      0),
    134: ('SUBIf'           , 13, 3,      0),
    135: ('MULIf'           , 13, 3,      0),
    136: ('SetG4'           , 16, 4,      0),
    137: ('ChkRefS'         ,  1, 1,      0),
    138: ('ChkNullV'        , 11, 1,      0),
    139: ('CALLINTF'        ,  4, 2,  65535),
    140: ('iTOb'            , 10, 2,      0),
    141: ('iTOw'            , 10, 2,      0),
    142: ('SetV1'           , 12, 2,      0),
    143: ('SetV2'           , 12, 2,      0),
    144: ('Cast'            ,  4, 2,     -2),
    145: ('i64TOi'          , 10, 2,      0),
    146: ('uTOi64'          , 10, 2,      0),
    147: ('iTOi64'          , 10, 2,      0),
    148: ('fTOi64'          , 10, 2,      0),
    149: ('dTOi64'          , 10, 2,      0),
    150: ('fTOu64'          , 10, 2,      0),
    151: ('dTOu64'          , 10, 2,      0),
    152: ('i64TOf'          , 10, 2,      0),
    153: ('u64TOf'          , 10, 2,      0),
    154: ('i64TOd'          , 10, 2,      0),
    155: ('u64TOd'          , 10, 2,      0),
    156: ('NEGi64'          , 11, 1,      0),
    157: ('INCi64'          ,  1, 1,      0),
    158: ('DECi64'          ,  1, 1,      0),
    159: ('BNOT64'          , 11, 1,      0),
    160: ('ADDi64'          ,  8, 2,      0),
    161: ('SUBi64'          ,  8, 2,      0),
    162: ('MULi64'          ,  8, 2,      0),
    163: ('DIVi64'          ,  8, 2,      0),
    164: ('MODi64'          ,  8, 2,      0),
    165: ('BAND64'          ,  8, 2,      0),
    166: ('BOR64'           ,  8, 2,      0),
    167: ('BXOR64'          ,  8, 2,      0),
    168: ('BSLL64'          ,  8, 2,      0),
    169: ('BSRL64'          ,  8, 2,      0),
    170: ('BSRA64'          ,  8, 2,      0),
    171: ('CMPi64'          , 14, 2,      0),
    172: ('CMPu64'          , 14, 2,      0),
    173: ('ChkNullS'        ,  2, 1,      0),
    174: ('ClrHi'           ,  1, 1,      0),
    175: ('JitEntry'        ,  6, 3,      0),
    176: ('CallPtr'         , 11, 1,  65535),
    177: ('FuncPtr'         ,  6, 3,      2),
    178: ('LoadThisR'       , 18, 2,      0),
    179: ('PshV8'           , 11, 1,      2),
    180: ('DIVu'            ,  8, 2,      0),
    181: ('MODu'            ,  8, 2,      0),
    182: ('DIVu64'          ,  8, 2,      0),
    183: ('MODu64'          ,  8, 2,      0),
    184: ('LoadRObjR'       , 19, 3,      0),
    185: ('LoadVObjR'       , 19, 3,      0),
    186: ('RefCpyV'         ,  3, 1,     -2),
    187: ('JLowZ'           ,  4, 2,      0),
    188: ('JLowNZ'          ,  4, 2,      0),
    189: ('AllocMem'        , 12, 2,      0),
    190: ('SetListSize'     , 20, 3,      0),
    191: ('PshListElmnt'    ,  5, 2,      2),
    192: ('SetListType'     , 20, 3,      0),
    193: ('POWi'            ,  8, 2,      0),
    194: ('POWu'            ,  8, 2,      0),
    195: ('POWf'            ,  8, 2,      0),
    196: ('POWd'            ,  8, 2,      0),
    197: ('POWdi'           ,  8, 2,      0),
    198: ('POWi64'          ,  8, 2,      0),
    199: ('POWu64'          ,  8, 2,      0),
    200: ('Thiscall1'       ,  6, 3,     -3),
    201: ('FinConstruct'    ,  6, 3,     -2),
    202: ('DestructScript'  , 17, 3,      0),
    203: ('CopyScript'      ,  6, 3,     -2),
    204: ('ResolveObjectPtr',  1, 1,      0),
    205: ('FreeNullV8'      ,  3, 1,      0),
    206: ('TrackRef'        , 11, 1,      0),
    207: ('UntrackRef'      , 11, 1,      0),
    208: ('ValidateRef'     , 11, 1,      0),
    209: ('CpyVtoR1'        , 11, 1,      0),
    210: ('SaveReturnValue' ,  1, 1,      0),
    211: ('CmpPtrNull'      , 11, 1,      0),
    212: ('ThrowException'  ,  2, 1,      0),
    251: ('VarDecl'         ,  2, 1,      0),
    252: ('Block'           ,  0, 0,      0),
    253: ('ObjInfo'         ,  5, 2,      0),
    254: ('LINE'            ,  0, 0,      0),
    255: ('LABEL'           ,  0, 0,      0),
}

NAME_TO_OP = {v[0]: k for k, v in OPCODES.items()}
